# Generated by Django 5.2.11 on 2026-02-28 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostAvailabilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturing_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('manufacturing_lead_time_days', models.PositiveIntegerField(default=14)),
                ('reorder_point', models.PositiveIntegerField(default=0, help_text='If on-hand qty drops below this, consider manufacturing/procurement.')),
                ('reorder_qty', models.PositiveIntegerField(default=0, help_text='Suggested replenishment qty for auto-triggering.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_profile', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_cost_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lead_time_days', models.PositiveIntegerField(default=7)),
                ('min_order_qty', models.PositiveIntegerField(default=1)),
                ('available_qty', models.PositiveIntegerField(default=0, help_text='Supplier-reported availability (optional).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offers', to='catalog.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='pricing.supplier')),
            ],
            options={
                'ordering': ['product__sku', 'purchase_cost_usd'],
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
