# Generated by Django 5.2.11 on 2026-04-25 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_compatibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('ref_no', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['ref_no'],
            },
        ),
        migrations.CreateModel(
            name='LookupFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('ref_no', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['ref_no'],
            },
        ),
        migrations.CreateModel(
            name='LookupFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('ref_no', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['ref_no'],
            },
        ),
        migrations.CreateModel(
            name='LookupFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('ref_no', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['ref_no'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in millimeters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.lookupdrive'),
        ),
        migrations.AddField(
            model_name='lookupdrive',
            name='applies_to_family',
            field=models.ManyToManyField(blank=True, related_name='drive_types', to='catalog.lookupfamily'),
        ),
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.lookupfamily'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.lookupfeature'),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.lookupfinish'),
        ),
        migrations.CreateModel(
            name='LookupHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('ref_no', models.PositiveIntegerField(default=100)),
                ('applies_to_family', models.ManyToManyField(blank=True, related_name='head_types', to='catalog.lookupfamily')),
            ],
            options={
                'ordering': ['ref_no'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.lookuphead'),
        ),
        migrations.CreateModel(
            name='LookupMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('ref_no', models.PositiveIntegerField(default=100)),
                ('applies_to_family', models.ManyToManyField(blank=True, related_name='material_types', to='catalog.lookupfamily')),
            ],
            options={
                'ordering': ['ref_no'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.lookupmaterial'),
        ),
        migrations.CreateModel(
            name='LookupThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('ref_no', models.PositiveIntegerField(default=100)),
                ('applies_to_family', models.ManyToManyField(blank=True, related_name='thread_types', to='catalog.lookupfamily')),
            ],
            options={
                'ordering': ['ref_no'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.lookupthread'),
        ),
    ]
